FROM ubuntu:16.04

COPY cserver.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
RUN apt-get -y update
RUN apt-get -y install openssh-server vim telnet sudo apt-transport-https
RUN ln -s /usr/bin/python3 /usr/bin/python
CMD service ssh start && /bin/bash
