FROM ubuntu:16.04

COPY cserver.pub /root/.ssh/id_rsa.pub
COPY cserver /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

RUN apt-get -y update

RUN apt-get -y install openssh-server vim telnet sudo apt-transport-https
RUN ln -s /usr/bin/python3 /usr/bin/python
