FROM ubuntu:14.04

COPY cserver.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
RUN apt-get -y update
RUN apt-get -y install openssh-server vim telnet
CMD service ssh start && /bin/bash
